### ISSUE TITLE
Doesn't seem to work on Go 1.4

### ISSUE THREAD

**Issue by alexjurkiewicz** [mvdan/sh#59]
Is this a known issue? Travis CI uses Go 1.4 as the default version.

```
$ go get -u github.com/mvdan/sh/cmd/shfmt
# github.com/mvdan/sh/cmd/shfmt
../../../.go/src/github.com/mvdan/sh/cmd/shfmt/main.go:165: undefined: io.CopyBuffer
The command "go get -u github.com/mvdan/sh/cmd/shfmt" failed and exited with 2 during .
```
from https://travis-ci.org/alexjurkiewicz/acts/builds/182188913

**Comment by mvdan** [comment]
This is expected; I only test on Go 1.7. I would usually make sure that the last few Go releases work well with it (in this case, 1.6 and perhaps 1.5 too). But I need subtests, which were added in 1.7.

In any case, CopyBuffer was added in 1.5 and I don't think it's worth working around it for compatibility with earlier releases. I suggest you either use Travis with a newer Go version or that you simply download a binary in travis: https://github.com/mvdan/sh/releases

**Comment by alexjurkiewicz** [comment]
Thanks for the clarification!
