### ISSUE TITLE
can not compile on debian/ubuntu

### ISSUE THREAD

**Issue by bittorf** [mvdan/sh#63]
```
# user@box ~ $ go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/386
```

```
# user@host ~ $ go get -u github.com/mvdan/sh/cmd/shfmt
# github.com/mvdan/sh/syntax
gocode/src/github.com/mvdan/sh/syntax/parser.go:23:23: error: reference to undefined identifier ‘sync.Pool’
 var parserFree = sync.Pool{
                       ^
gocode/src/github.com/mvdan/sh/syntax/parser.go:23:27: error: expected ‘;’ or newline after top level declaration
 var parserFree = sync.Pool{
                           ^
gocode/src/github.com/mvdan/sh/syntax/parser.go:26:2: error: expected declaration
  },
  ^
gocode/src/github.com/mvdan/sh/syntax/printer.go:17:24: error: reference to undefined identifier ‘sync.Pool’
 var printerFree = sync.Pool{
                        ^
gocode/src/github.com/mvdan/sh/syntax/printer.go:17:28: error: expected ‘;’ or newline after top level declaration
 var printerFree = sync.Pool{
                            ^
gocode/src/github.com/mvdan/sh/syntax/printer.go:23:2: error: expected declaration
  },
  ^
```

**Comment by mvdan** [comment]
> The GCC 4.9 releases include a complete Go 1.2 implementation.

And from the README:

> Requires Go 1.6 or later.

`sync.Pool` was added in 1.3. I think this package will build with 1.4 and later, but haven't tested. In any case, I see no need to be buildable with more than a few last major versions of Go.

You can always use your current compiler to bootstrap a new version of Go, or simply download a binary from the releases page.

**Comment by bittorf** [comment]
thank you, i could not read the go-version from the GCC version - this explains the issue.
